### ISSUE TITLE
Unhandled rejection Error: watch ..\..\bootstrap ENOENT

### ISSUE THREAD

**Issue by BerndWessels** [shakacode/bootstrap-loader#108]
Hi

The `preBootstrapCustomizations: ./bootstrap/pre.scss` and `bootstrapCustomizations: ./bootstrap/post.scss` causes an error.

If I move the `pre.scss` and `post.scss` into the root folder the error disappears but webpack keeps on recompiling constantly.

I get the error below which breaks my project's "watch and reload on change" with the following `.bootstraprc`:

```
    ---
    # Output debugging info
    # loglevel: debug

    # Major version of Bootstrap: 3 or 4
    bootstrapVersion: 4

    # If Bootstrap version 4 is used - turn on/off flexbox model
    useFlexbox: true

    # Webpack loaders, order matters
    styleLoaders:
      - style
      - css
      - postcss
      - sass

    # Extract styles to stand-alone css file
    # Different settings for different environments can be used,
    # It depends on value of NODE_ENV environment variable
    # This param can also be set in webpack config:
    #   entry: 'bootstrap-loader/extractStyles'
    #extractStyles: false
    # env:
    #   development:
    #     extractStyles: false
    #   production:
    #     extractStyles: true

    # Customize Bootstrap variables that get imported before the original Bootstrap variables.
    # Thus original Bootstrap variables can depend on values from here.
    preBootstrapCustomizations: ./bootstrap/pre.scss

    # This gets loaded after bootstrap/variables is loaded
    # So you can refer to bootstrap variables
    bootstrapCustomizations: ./bootstrap/post.scss

    # With CSS Modules we load all application styles directly in React components
    # appStyles: ./app/styles/app.scss

    ### Bootstrap styles
    styles:

      # Mixins
      mixins: true

      # Reset and dependencies
      normalize: true
      print: true

      # Core CSS
      reboot: true
      type: true
      images: true
      code: true
      grid: true
      tables: true
      forms: true
      buttons: true

      # Components
      animation: true
      dropdown: true
      button-group: true
      input-group: true
      custom-forms: true
      nav: true
      navbar: true
      card: true
      breadcrumb: true
      pagination: true
      pager: true
      labels: true
      jumbotron: true
      alert: true
      progress: true
      media: true
      list-group: true
      responsive-embed: true
      close: true

      # Components w/ JavaScript
      modal: true
      tooltip: true
      popover: true
      carousel: true

      # Utility classes
      utilities: true
      utilities-spacing: true
      utilities-responsive: true

    ### Bootstrap scripts
    scripts: false
```

Here is the console error:

```
    Unhandled rejection Error: watch ..\..\bootstrap ENOENT
        at exports._errnoException (util.js:870:11)
        at FSWatcher.start (fs.js:1234:19)
        at Object.fs.watch (fs.js:1262:11)
        at processItem (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\node\OldNodeWatchFileSystem.js:130:21)
        at C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\async\lib\async.js:181:20
        at Object.async.forEachOf.async.eachOf (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\async\lib\async.js:233:13)
        at Object.async.forEach.async.each (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\async\lib\async.js:209:22)
        at OldNodeWatchFileSystem.watch (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\node\OldNodeWatchFileSystem.js:127:8)
        at Watching.watch (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:87:47)
        at Watching._done (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:83:8)
        at Watching.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:61:18)
        at Compiler.emitRecords (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:282:37)
        at Watching.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:58:19)
        at C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:275:11
        at Compiler.applyPluginsAsync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:60:69)
        at Compiler.afterEmit (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:272:8)
        at Compiler.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:267:14)
        at C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\async\lib\async.js:52:16
        at Object.async.forEachOf.async.eachOf (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\async\lib\async.js:236:30)
        at Object.async.forEach.async.each (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\async\lib\async.js:209:22)
        at Compiler.emitFiles (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:235:20)
        at MemoryFileSystem.(anonymous function) [as mkdirp] (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\memory-fs\lib\MemoryFileSystem.js:283:10)
    From previous event:
        at Compiler.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\html-webpack-plugin\index.js:197:15)
        at Compiler.applyPluginsAsync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:71:13)
        at Compiler.emitAssets (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:226:7)
        at Watching.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:54:18)
        at C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:403:12
        at Compiler.next (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:67:11)
        at Compiler.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\CachePlugin.js:40:4)
        at Compiler.applyPluginsAsync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:71:13)
        at Compiler.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compiler.js:400:9)
        at Compilation.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compilation.js:577:13)
        at Compilation.next (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:67:11)
        at Compilation.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\ProgressPlugin.js:69:5)
        at Compilation.applyPluginsAsync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:71:13)
        at Compilation.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compilation.js:572:10)
        at Compilation.next (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:67:11)
        at Compilation.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\ProgressPlugin.js:65:5)
        at Compilation.applyPluginsAsync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:71:13)
        at Compilation.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compilation.js:567:9)
        at Compilation.next (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:67:11)
        at ExtractTextPlugin.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\extract-text-webpack-plugin\index.js:309:4)
        at Compilation.applyPluginsAsync (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:71:13)
        at Compilation.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\webpack\lib\Compilation.js:563:8)
        at Compilation.next (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\tapable\lib\Tapable.js:67:11)
        at ExtractTextPlugin.<anonymous> (C:\Users\bwessels.SPENDV\Documents\WebstormProjects\Fraedom.Air\microsite\node_modules\extract-text-webpack-plugin\index.js:285:5)
```
