### ISSUE TITLE
build fails using bootstrap-3 resulting in "undefined:0 TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by cam-vanorman** [shakacode/bootstrap-loader#229]
I'm unable to figure out what's wrong with my build configuration. Here's the debug output of my bootstrap-3 build with DEBUG mode:

```
[bootstrap-loader]:  bootstrap-loader is in DEBUG mode because you have your config log level set to 'debug'.

[bootstrap-loader]:  Using config file /Users/cameron/Code/big-commerce-efelle-base/.bootstraprc

[bootstrap-loader]:  Query from webpack config: *none*

[bootstrap-loader]:  Using Bootstrap module: bootstrap-sass

[bootstrap-loader]:  Bootstrap module location (abs): /Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-sass

[bootstrap-loader]:  Bootstrap module location (rel): ../bootstrap-sass

[bootstrap-loader]:  Context: /Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-loader

[bootstrap-loader]:  Using Bootstrap version: 3

[bootstrap-loader]:  Bootstrap NPM package version: 3.3.7

[bootstrap-loader]:  Normalized params:
 { bootstrapVersion: 3,
  loglevel: 'debug',
  preBootstrapCustomizations: '/Users/cameron/Code/big-commerce-efelle-base/assets/styles/bootstrap/pre-customizations.scss',
  bootstrapCustomizations: undefined,
  appStyles: '/Users/cameron/Code/big-commerce-efelle-base/assets/styles/app.scss',
  disableSassSourceMap: undefined,
  disableResolveUrlLoader: undefined,
  useFlexbox: undefined,
  useCustomIconFontPath: false,
  extractStyles: false,
  styleLoaders:
   [ 'style-loader',
     'css-loader?sourceMap',
     'resolve-url-loader?sourceMap',
     'sass-loader?sourceMap' ],
  styles:
   [ 'mixins',
     'normalize',
     'print',
     'scaffolding',
     'type',
     'code',
     'grid',
     'tables',
     'forms',
     'buttons',
     'component-animations',
     'dropdowns',
     'button-groups',
     'input-groups',
     'navs',
     'navbar',
     'breadcrumbs',
     'pagination',
     'pager',
     'labels',
     'badges',
     'jumbotron',
     'thumbnails',
     'alerts',
     'progress-bars',
     'media',
     'list-group',
     'panels',
     'wells',
     'responsive-embed',
     'close',
     'modals',
     'tooltip',
     'popovers',
     'carousel',
     'utilities',
     'responsive-utilities' ],
  scripts:
   [ 'transition',
     'alert',
     'button',
     'carousel',
     'collapse',
     'dropdown',
     'modal',
     'tooltip',
     'popover',
     'scrollspy',
     'tab',
     'affix' ],
  configFilePath: '/Users/cameron/Code/big-commerce-efelle-base/.bootstraprc',
  bootstrapPath: '/Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-sass',
  bootstrapRelPath: '../bootstrap-sass' }

[bootstrap-loader]:  Requiring:
 module.exports.css = require ("style-loader!css-loader?sourceMap!resolve-url-loader?sourceMap!sass-loader?sourceMap!./lib/bootstrap.styles.loader.js?{\"bootstrapVersion\":3,\"loglevel\":\"debug\",\"preBootstrapCustomizations\":\"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/bootstrap/pre-customizations.scss\",\"appStyles\":\"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/app.scss\",\"useCustomIconFontPath\":false,\"extractStyles\":false,\"styleLoaders\":[\"style-loader\",\"css-loader?sourceMap\",\"resolve-url-loader?sourceMap\",\"sass-loader?sourceMap\"],\"styles\":[\"mixins\",\"normalize\",\"print\",\"scaffolding\",\"type\",\"code\",\"grid\",\"tables\",\"forms\",\"buttons\",\"component-animations\",\"dropdowns\",\"button-groups\",\"input-groups\",\"navs\",\"navbar\",\"breadcrumbs\",\"pagination\",\"pager\",\"labels\",\"badges\",\"jumbotron\",\"thumbnails\",\"alerts\",\"progress-bars\",\"media\",\"list-group\",\"panels\",\"wells\",\"responsive-embed\",\"close\",\"modals\",\"tooltip\",\"popovers\",\"carousel\",\"utilities\",\"responsive-utilities\"],\"scripts\":[\"transition\",\"alert\",\"button\",\"carousel\",\"collapse\",\"dropdown\",\"modal\",\"tooltip\",\"popover\",\"scrollspy\",\"tab\",\"affix\"],\"configFilePath\":\"/Users/cameron/Code/big-commerce-efelle-base/.bootstraprc\",\"bootstrapPath\":\"/Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-sass\",\"bootstrapRelPath\":\"../bootstrap-sass\"}!./no-op.js");
module.exports.js = require ("./lib/bootstrap.scripts.loader.js?{\"bootstrapVersion\":3,\"loglevel\":\"debug\",\"preBootstrapCustomizations\":\"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/bootstrap/pre-customizations.scss\",\"appStyles\":\"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/app.scss\",\"useCustomIconFontPath\":false,\"extractStyles\":false,\"styleLoaders\":[\"style-loader\",\"css-loader?sourceMap\",\"resolve-url-loader?sourceMap\",\"sass-loader?sourceMap\"],\"styles\":[\"mixins\",\"normalize\",\"print\",\"scaffolding\",\"type\",\"code\",\"grid\",\"tables\",\"forms\",\"buttons\",\"component-animations\",\"dropdowns\",\"button-groups\",\"input-groups\",\"navs\",\"navbar\",\"breadcrumbs\",\"pagination\",\"pager\",\"labels\",\"badges\",\"jumbotron\",\"thumbnails\",\"alerts\",\"progress-bars\",\"media\",\"list-group\",\"panels\",\"wells\",\"responsive-embed\",\"close\",\"modals\",\"tooltip\",\"popovers\",\"carousel\",\"utilities\",\"responsive-utilities\"],\"scripts\":[\"transition\",\"alert\",\"button\",\"carousel\",\"collapse\",\"dropdown\",\"modal\",\"tooltip\",\"popover\",\"scrollspy\",\"tab\",\"affix\"],\"configFilePath\":\"/Users/cameron/Code/big-commerce-efelle-base/.bootstraprc\",\"bootstrapPath\":\"/Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-sass\",\"bootstrapRelPath\":\"../bootstrap-sass\"}!./no-op.js");


[bootstrap-loader]:  Scripts input config:
 ?{"bootstrapVersion":3,"loglevel":"debug","preBootstrapCustomizations":"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/bootstrap/pre-customizations.scss","appStyles":"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/app.scss","useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style-loader","css-loader?sourceMap","resolve-url-loader?sourceMap","sass-loader?sourceMap"],"styles":["mixins","normalize","print","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/cameron/Code/big-commerce-efelle-base/.bootstraprc","bootstrapPath":"/Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}

[bootstrap-loader]:  Scripts output:
 require ("../bootstrap-sass/assets/javascripts/bootstrap/transition");
require ("../bootstrap-sass/assets/javascripts/bootstrap/alert");
require ("../bootstrap-sass/assets/javascripts/bootstrap/button");
require ("../bootstrap-sass/assets/javascripts/bootstrap/carousel");
require ("../bootstrap-sass/assets/javascripts/bootstrap/collapse");
require ("../bootstrap-sass/assets/javascripts/bootstrap/dropdown");
require ("../bootstrap-sass/assets/javascripts/bootstrap/modal");
require ("../bootstrap-sass/assets/javascripts/bootstrap/tooltip");
require ("../bootstrap-sass/assets/javascripts/bootstrap/popover");
require ("../bootstrap-sass/assets/javascripts/bootstrap/scrollspy");
require ("../bootstrap-sass/assets/javascripts/bootstrap/tab");
require ("../bootstrap-sass/assets/javascripts/bootstrap/affix");


[bootstrap-loader]:  Styles input config:
 ?{"bootstrapVersion":3,"loglevel":"debug","preBootstrapCustomizations":"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/bootstrap/pre-customizations.scss","appStyles":"/Users/cameron/Code/big-commerce-efelle-base/assets/styles/app.scss","useCustomIconFontPath":false,"extractStyles":false,"styleLoaders":["style-loader","css-loader?sourceMap","resolve-url-loader?sourceMap","sass-loader?sourceMap"],"styles":["mixins","normalize","print","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/cameron/Code/big-commerce-efelle-base/.bootstraprc","bootstrapPath":"/Users/cameron/Code/big-commerce-efelle-base/node_modules/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}

[bootstrap-loader]:  Styles output:
 @import "../bootstrap-sass/assets/stylesheets/bootstrap/_mixins";
@import "../../assets/styles/bootstrap/pre-customizations.scss";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_variables";
$icon-font-path: "../bootstrap-sass/assets/fonts/bootstrap/";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_normalize";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_print";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_scaffolding";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_type";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_code";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_grid";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_tables";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_forms";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_buttons";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_component-animations";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_dropdowns";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_button-groups";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_input-groups";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_navs";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_navbar";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_breadcrumbs";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_pagination";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_pager";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_labels";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_badges";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_jumbotron";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_thumbnails";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_alerts";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_progress-bars";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_media";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_list-group";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_panels";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_wells";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_responsive-embed";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_close";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_modals";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_tooltip";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_popovers";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_carousel";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_utilities";
@import "../bootstrap-sass/assets/stylesheets/bootstrap/_responsive-utilities";
@import "../../assets/styles/app.scss";


undefined:0



TypeError: undefined is not a function
```

Here's my `.bootstraprc` config file

```
---
# Output debugging info
loglevel: debug

# Major version of Bootstrap: 3 or 4
bootstrapVersion: 3

# If Bootstrap version 3 is used - turn on/off custom icon font path
useCustomIconFontPath: false

# Webpack loaders, order matters
styleLoaders:
  - style-loader
  - css-loader?sourceMap
  - resolve-url-loader?sourceMap
  - sass-loader?sourceMap

# Extract styles to stand-alone css file
# Different settings for different environments can be used,
# It depends on value of NODE_ENV environment variable
# This param can also be set in webpack config:
#   entry: 'bootstrap-loader/extractStyles'
#extractStyles: false
# env:
#   development:
#     extractStyles: false
#   production:
#     extractStyles: true

# Customize Bootstrap variables that get imported before the original Bootstrap variables.
# Thus original Bootstrap variables can depend on values from here. All the bootstrap
# variables are configured with !default, and thus, if you define the variable here, then
# that value is used, rather than the default. However, many bootstrap variables are derived
# from other bootstrap variables, and thus, you want to set this up before we load the
# official bootstrap versions.
# For example, _variables.scss contains:
# $input-color: $gray !default;
# This means you can define $input-color before we load _variables.scss
preBootstrapCustomizations: ./assets/styles/bootstrap/pre-customizations.scss

# This gets loaded after bootstrap/variables is loaded and before bootstrap is loaded.
# A good example of this is when you want to override a bootstrap variable to be based
# on the default value of bootstrap. This is pretty specialized case. Thus, you normally
# just override bootrap variables in preBootstrapCustomizations so that derived
# variables will use your definition.
#
# For example, in _variables.scss:
# $input-height: (($font-size-base * $line-height) + ($input-padding-y * 2) + ($border-width * 2)) !default;
# This means that you could define this yourself in preBootstrapCustomizations. Or you can do
# this in bootstrapCustomizations to make the input height 10% bigger than the default calculation.
# Thus you can leverage the default calculations.
# $input-height: $input-height * 1.10;
#bootstrapCustomizations: false

# Import your custom styles here. You have access to all the bootstrap variables. If you require
# your sass files separately, you will not have access to the bootstrap variables, mixins, clases, etc.
# Usually this endpoint-file contains list of @imports of your application styles.
appStyles: ./assets/styles/app.scss

### Bootstrap styles
styles:

  # Mixins
  mixins: true

  # Reset and dependencies
  normalize: true
  print: true
  glyphicons: false

  # Core CSS
  scaffolding: true
  type: true
  code: true
  grid: true
  tables: true
  forms: true
  buttons: true

  # Components
  component-animations: true
  dropdowns: true
  button-groups: true
  input-groups: true
  navs: true
  navbar: true
  breadcrumbs: true
  pagination: true
  pager: true
  labels: true
  badges: true
  jumbotron: true
  thumbnails: true
  alerts: true
  progress-bars: true
  media: true
  list-group: true
  panels: true
  wells: true
  responsive-embed: true
  close: true

  # Components w/ JavaScript
  modals: true
  tooltip: true
  popovers: true
  carousel: true

  # Utility classes
  utilities: true
  responsive-utilities: true

### Bootstrap scripts
scripts:
  transition: true
  alert: true
  button: true
  carousel: true
  collapse: true
  dropdown: true
  modal: true
  tooltip: true
  popover: true
  scrollspy: true
  tab: true
  affix: true
```

Finally, here's my package.json:

```
{
  "name": "bigcommerce",
  "description": "Custom BigCommerce Template",
  "version": "1.0.0",
  "author": "",
  "private": true,
  "dependencies": {
    "handlebars": "^4.0.6",
    "handlebars-loader": "^1.4.0"
  },
  "devDependencies": {
    "@bigcommerce/citadel": "^2.11.5",
    "@bigcommerce/stencil-utils": "1.0.5",
    "autoprefixer": "^6.5.3",
    "async": "^2.1.4",
    "axios": "^0.15.3",
    "babel-core": "6.7.4",
    "babel-eslint": "4.1.0",
    "babel-loader": "6.2.4",
    "babel-polyfill": "^6.8.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "bootstrap-loader": "^1.3.2",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "jquery": "^3.1.1",
    "node-sass": "^4.1.0",
    "page": "^1.7.1",
    "resolve-url-loader": "^1.6.1",
    "sass-loader": "^4.1.0",
    "sass-resources-loader": "^1.1.0",
    "slick-carousel": "^1.6.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14"
  }
}
```

If anyone can provide any assistance/debugging information for me, I'm new to both webkit and this loader.
