### ISSUE TITLE
Load Order

### ISSUE THREAD

**Issue by tomasbarrios** [shakacode/bootstrap-loader#234]
Hi, I am facing an issue with bootstrap-loader.

When importing bootstrap, it adds the bootstrap css tag **after** what is in bootstrap-customizations.scss. And those are meant to override bootstrap variables.

![captura de pantalla 2017-01-05 a las 18 19 42](https://cloud.githubusercontent.com/assets/552460/21698023/ec7fdf84-d373-11e6-8ef1-7bd836b8271f.png)

As you can see in the picture above, Bootstrap styles are loaded **last instead of first**

![captura de pantalla 2017-01-05 a las 18 20 20](https://cloud.githubusercontent.com/assets/552460/21698024/ec805144-d373-11e6-9c4f-a9329c846440.png)

bootstrap-customizations.scss

```scss
@import "~bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css";
@import "~bootstrap-social/bootstrap-social.css";
@import "~slick-carousel/slick/slick.css";
@import "~slick-carousel/slick/slick-theme.css";
```
.bootstraprc

```yaml
---
# Output debugging info
# loglevel: debug

# Major version of Bootstrap: 3 or 4
bootstrapVersion: 3

# If Bootstrap version 3 is used - turn on/off custom icon font path
useCustomIconFontPath: false

# Webpack loaders, order matters
styleLoaders:
  - style
  - css
  - sass

# Extract styles to stand-alone css file
# Different settings for different environments can be used,
# It depends on value of NODE_ENV environment variable
# This param can also be set in webpack config:
#   entry: 'bootstrap-loader/extractStyles'
extractStyles: false
# env:
#   development:
#     extractStyles: false
#   production:
#     extractStyles: true

# Customize Bootstrap variables that get imported before the original Bootstrap variables.
# Thus original Bootstrap variables can depend on values from here.
# preBootstrapCustomizations: ./app/assets/styles/bootstrap-pre-customizations.scss

# This gets loaded after bootstrap/variables is loaded
# So you can refer to bootstrap variables
bootstrapCustomizations: ./app/assets/styles/bootstrap-customizations.scss

# With CSS Modules we load all application styles directly in React components
# appStyles: ./app/styles/app.scss

### Bootstrap styles
styles:

  # Mixins
  mixins: true

  # Reset and dependencies
  normalize: false
  print: false
  glyphicons: false

  # Core CSS
  scaffolding: true
  type: true
  code: true
  grid: true
  tables: true
  forms: true
  buttons: true

  # Components
  component-animations: true
  dropdowns: true
  button-groups: true
  input-groups: true
  navs: true
  navbar: true
  breadcrumbs: true
  pagination: true
  pager: true
  labels: true
  badges: true
  jumbotron: true
  thumbnails: true
  alerts: true
  progress-bars: true
  media: true
  list-group: true
  panels: true
  wells: true
  responsive-embed: true
  close: true

  # Components w/ JavaScript
  modals: true
  tooltip: true
  popovers: true
  carousel: true

  # Utility classes
  utilities: true
  responsive-utilities: true

### Bootstrap scripts
scripts:
  transition: true
  alert: true
  button: true
  carousel: true
  collapse: true
  dropdown: true
  modal: true
  tooltip: true
  popover: true
  scrollspy: true
  tab: true
  affix: true
```
