### ISSUE TITLE
Could not find 'styleLoaders' in your config

### ISSUE THREAD

**Issue by bbousba** [shakacode/bootstrap-loader#275]
webpack@2.2.1
webpack-dev-server@2.4.1
bootstrap-loader@2.0.0-exports.1

Hi,

I've got this error when using with webpak.

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error: 
Could not find 'styleLoaders' in your config.
You can use default ones:
  styleLoaders: ['style', 'css', 'sass']

```

Here is my **.bootstraprc** file :

```
env:
  development:
    # Webpack loaders, order matters
    styleLoaders:
      - style-loader
      - css-loader?sourceMap
      - resolve-url-loader?sourceMap
      - sass-loader?sourceMap

    # Inline styles
    extractStyles: false

  production:
    styleLoaders:
      - style-loader
      - css-loader
      - sass-loader

    # Extract styles to stand-alone css file
    extractStyles: true
```

In my webpack.config.js, I define NODE_ENV like this :

```
    new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify('development'),
        },
      }),
```
