### ISSUE TITLE
no-op.js very large in Webpack v3 bundle

### ISSUE THREAD

**Issue by JaKXz** [shakacode/bootstrap-loader#322]
This might be a red herring, and a completely invalid issue, but I have been wondering about it for a while so I _need_ to ask.

In my project, we are using `bootstrap` v3.3.7, `bootstrap-loader` v2.1.0, and `webpack` v3.5.4 with the following <summary>.bootstraprc file:
<details>

```yml
---
# Output debugging info
# loglevel: debug

# Major version of Bootstrap: 3 or 4
bootstrapVersion: 3

# If Bootstrap version 3 is used - turn on/off custom icon font path
useCustomIconFontPath: false

# Webpack loaders, order matters
styleLoaders:
  - style
  - css
  - sass

# Extract styles to stand-alone css file
# Different settings for different environments can be used,
# It depends on value of NODE_ENV environment variable
# This param can also be set in webpack config:
#   entry: 'bootstrap-loader/extractStyles'
extractStyles: false
# env:
#   development:
#     extractStyles: false
#   production:
#     extractStyles: true


# Customize Bootstrap variables that get imported before the original Bootstrap variables.
# Thus, derived Bootstrap variables can depend on values from here.
# See the Bootstrap _variables.scss file for examples of derived Bootstrap variables.
#
preBootstrapCustomizations: ../app/assets/stylesheets/bootstrap-variables.sass


# This gets loaded after bootstrap/variables is loaded
# Thus, you may customize Bootstrap variables
# based on the values established in the Bootstrap _variables.scss file
#
# bootstrapCustomizations: ./path/to/bootstrap/customizations.scss


# Import your custom styles here
# Usually this endpoint-file contains list of @imports of your application styles
#
# appStyles: ./path/to/your/app/styles/endpoint.scss


### Bootstrap styles
styles:

  # Mixins
  mixins: true

  # Reset and dependencies
  normalize: true
  print: true
  glyphicons: true

  # Core CSS
  scaffolding: true
  type: true
  code: true
  grid: true
  tables: true
  forms: true
  buttons: true

  # Components
  component-animations: true
  dropdowns: false
  button-groups: true
  input-groups: true
  navs: true
  navbar: true
  breadcrumbs: true
  pagination: true
  pager: true
  labels: true
  badges: true
  jumbotron: true
  thumbnails: true
  alerts: true
  progress-bars: true
  media: true
  list-group: true
  panels: true
  wells: true
  responsive-embed: true
  close: true

  # Components w/ JavaScript
  modals: false
  tooltip: false
  popovers: false
  carousel: false

  # Utility classes
  utilities: true
  responsive-utilities: true

### Bootstrap scripts
scripts:
  affix: false
  alert: false
  button: false
  carousel: false
  collapse: false
  dropdown: false
  modal: false
  popover: false
  scrollspy: false
  tab: false
  tooltip: false
  transition: false
```
</details>
</summary>

And webpack `entry`: 
```js
[
  "bootstrap-loader",
  "./app",
]
```

With this config, `webpack-bundle-analyzer` tells me that bootstrap-loader/no-op.js is _huge_:

<img width="1410" alt="screen shot 2017-08-24 at 4 39 43 pm" src="https://user-images.githubusercontent.com/2642545/29687706-5973d258-88eb-11e7-9e11-e421600aa70b.png">

17KB gzipped from a supposedly 35 raw byte file that does `module.exports = {};`. 

I also took a look at the bundle in the new `webpack-dashboard` and it reported that bootstrap-loader/no-op.js is 3% of my total bundle size.

At this point I have no clue why this is, and like I mentioned I think it could be a red herring or a bug in the tools I'm using to measure the bundle size. 

Any help would be greatly appreciated. Please let me know if I can provide any more information to help investigate. Thanks!
