### ISSUE TITLE
yarn build extractStyles

### ISSUE THREAD

**Issue by jw-miaem** [shakacode/bootstrap-loader#398]
Hi Trying to use extractstyles in production and get this Error

`Error: You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started`

it's an old project trying to upgrade and this is the only blocker currently, any ideas? this is the config, following examples folder but with different dependency tree

```
production:
    extractStyles: true
    styleLoaders:
      - css-loader
      - sass-loader
      - postcss-loader
```
