### ISSUE TITLE
Allow picking bootstrap 3/4 (locked) with default configuration file.

### ISSUE THREAD

**Issue by justin808** [shakacode/bootstrap-loader#5]
Below is possible feature enhancement.

**HOWEVER**, after some more discussions on this, we really want to encourage projects to use their own copy of the `.bootstraprc` file, as that allows specifying a post-loading bootstrap customization file. Here's an [example](https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-3-default#L44).

-------------------------

The problem is that default configuration file is at a specific bootstrap version.

So if you don't specify a configuration file, you get bootstrap 3 now, but someday in the future, you might unexpectedly upgrade to bootstrap 4.

*We will probably bump the major version of the bootstrap-loader when we go to Bootstrap v4*.

Maybe we should offer a syntax like:

`require('bootrap-loader?version=3)` to use the bootstrap version 3 config.

Alternately, if no config file is specified, could we just check which peer dependency is available and go with that?

(side note: We allow the require of this: `bootstrap-loader/extractStyles` to specify the default for extractStyles to be on for production)

CC: @alexfedoseev

**Comment by alex88** [comment]
What's the current behaviour?

I had a couple headaches since I created a config file to disable scripts since I use react-bootstrap, then it asked to declare the bootstrap version, after that, without warnings etc there were no styles in the page until I declared the remaining parts, wouldn't be ok to use bootstrap config as defaults depending on the version declared in the config?

**Comment by justin808** [comment]
Default is version 3. Best to create a config file, @alex88.

**Comment by alex88** [comment]
Yeah, that's what I did, I wanted to knew if the missing keys in the config files are being inherited by the default config or not, that would be great

**Comment by justin808** [comment]
@alex88 can you maybe tell us a bit more about what was missing? Even better would be a PR that would have allowed you to use the default config file.

**Comment by alexfedoseev** [comment]
> Yeah, that's what I did, I wanted to knew if the missing keys in the config files are being inherited by the default config or not, that would be great

Nope, they're not inherited b/c this kind of magic often leads to confusing:

```yml
# user config
styles:
  normalize: true    # <--- User config contains only `normalize` item

# default config
styles:
  normalize: true
  print: true        # <--- The rest items will be loaded, not clear for the user why it's happening
  glyphicons: true
  ...
```
