### ISSUE TITLE
bootstrapCustomizations Isn't Loading?

### ISSUE THREAD

**Issue by digia** [shakacode/bootstrap-loader#55]
It doesn't appear that the bootstrapCustomizations file is being loaded and overriding the Bootstrap variables. Below is my .bootstraprc file.

Any assistance/direction would be greatly appreciated. Thank you!

```yaml
# Output debugging info
# loglevel: debug

# Major version of Bootstrap: 3 or 4
bootstrapVersion: 4

# If Bootstrap version 4 is used - turn on/off flexbox model
useFlexbox: false

# Webpack loaders, order matters
styleLoaders:
  - style
  - css
  - sass

# Extract styles to stand-alone css file
# Different settings for different environments can be used,
# It depends on value of NODE_ENV environment variable
# This param can also be set in webpack config:
#   entry: 'bootstrap-loader/extractStyles'
extractStyles: true
# env:
#   development:
#     extractStyles: false
#   production:
#     extractStyles: true


# Customize Bootstrap variables that get imported before the original Bootstrap variables.
# Thus, derived Bootstrap variables can depend on values from here.
# See the Bootstrap _variables.scss file for examples of derived Bootstrap variables.
#
# preBootstrapCustomizations: ./path/to/bootstrap/pre-customizations.scss


# This gets loaded after bootstrap/variables is loaded
# Thus, you may customize Bootstrap variables
# based on the values established in the Bootstrap _variables.scss file
#
bootstrapCustomizations: ./scss/_variables.scss

# Import your custom styles here
# Usually this endpoint-file contains list of @imports of your application styles
#
# appStyles: ./path/to/your/app/styles/endpoint.scss


### Bootstrap styles
styles:

  # Mixins
  mixins: true

  # Reset and dependencies
  normalize: true
  print: true

  # Core CSS
  reboot: true
  type: true
  images: true
  code: true
  grid: true
  tables: true
  forms: true
  buttons: true

  # Components
  animation: false
  dropdown: false
  button-group: false
  input-group: false
  custom-forms: false
  nav: true
  navbar: true
  card: false
  breadcrumb: false
  pagination: false
  pager: false
  labels: false
  jumbotron: false
  alert: false
  progress: false
  media: false
  list-group: false
  responsive-embed: false
  close: false

  # Components w/ JavaScript
  modal: false
  tooltip: false
  popover: false
  carousel: false

  # Utility classes
  utilities: true
  utilities-background: true
  utilities-spacing: true
  utilities-responsive: true

### Bootstrap scripts
scripts:
  alert: false
  button: false
  carousel: false
  collapse: false
  dropdown: false
  modal: false
  popover: false
  scrollspy: false
  tab: false
  tooltip: false
  util: true

```
