### ISSUE TITLE
Cannot disable normalize

### ISSUE THREAD

**Issue by srahulprdxn** [shakacode/bootstrap-loader#83]
I tried the below given config:

```
### Bootstrap styles
styles:

  # Mixins
  mixins: true

  # Reset and dependencies
  print: true
  glyphicons: true

  # Core CSS
  scaffolding: true
  type: true
  code: true
  grid: true
  tables: true
  forms: true
  buttons: true
```

and

```
### Bootstrap styles
styles:

  # Mixins
  mixins: true

  # Reset and dependencies
  normalize: false
  print: true
  glyphicons: true

  # Core CSS
  scaffolding: true
  type: true
  code: true
  grid: true
  tables: true
  forms: true
  buttons: true
```

None of 'em worked. Normalize.css gets appended and is loaded. I wanna get rid of this css.
